[package]
name = "zkRollup"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
hex = "0.4.3"
serde = "1.0.204"
sha2 = "0.10.8"
sov-rollup-interface = "0.3.0"

[dev-dependencies]
proptest = "1.5.0"